<?php
if (!defined('IN_CONTEXT')) die('access violation error!');

$o_site_menu = new AdminMenuItem();
$site_items = $o_site_menu->findAll("category_id=1 and level <= '".EZSITE_LEVEL."' ORDER BY priority");
?>
		<div class="fl">
            <h1><span class="icon2"><?php _e('Settings')?></span></h1>
            <ul>
            	<?php 
            	foreach($site_items as $v) {
            		$str2 = Html::uriquery($v->module, $v->action);
            		$text = __($v->text);
            		echo "<li class='icon3'><a href='$str2'>$text</a></li>";
            	}
            	?>
            </ul>
        </div>
        <div class="fr1">
            <div style=" margin:10px; border:solid 1px #ccc;">
            	<h5><div class="in_t">&nbsp;</div><?php _e('The website disposition is the guarantee of the website access, all informations that needed fulfill in order of the webpage visiting.');?></h5>
					<?php if(EZSITE_LEVEL=='2'){?>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_1" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; line-height:40px; margin-left:30px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_site', 'admin_list'); ?>"><?php _e('Web Settings');?></a></div><div style="overflow:hidden; line-height:40px;_width:400px; _overflow:hidden;"><?php _e('The basic setting for website, the key words of the website name setting, website logo,website introduction, contact us.');?></div></div>
                   	<div style="border-bottom:dotted 1px #CCC;"><div class="index_2" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_qq', 'admin_list'); ?>"><?php _e('Services');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('You can settle this function here, the normal online and immediate communication tool for helping.');?></div></div>
					<div style="border-bottom:dotted 1px #CCC;"><div class="index_3" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_payaccount', 'admin_list'); ?>"><?php _e('Payment Accounts');?></a> </div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('You can fix the connector for online payment which enables you to buy the product online.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_4" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_statistics', 'admin_list'); ?>"><?php _e('Statistics');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('If you want to know the volume of visiting, where these visiting come from..Etc, please add the calculation code.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_5" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="index.php?_m=mod_friendlink&_a=admin_list"><?php _e('Hot Links');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Please add the favorite links here.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_6" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_backup', 'admin_list'); ?>"><?php _e('Data Bakup/Recovery');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Backup data or import data.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_7" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_attachment', 'admin_list'); ?>"><?php _e('Image Watermark/Thumb');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Image watermark or thumb setting.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_8" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_advert', 'admin_list'); ?>"><?php _e('Advert Tool');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Advert setting.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_9" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_sitestarmaker', 'admin_list'); ?>"><?php _e('Picture Tool');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Logo and Banner setting.');?></div></div>
					<?php } else {?>
					<div style="border-bottom:dotted 1px #CCC;"><div class="index_1" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; line-height:40px; margin-left:30px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_site', 'admin_list'); ?>"><?php _e('Web Settings');?></a></div><div style="overflow:hidden; line-height:40px;_width:400px; _overflow:hidden;"><?php _e('The basic setting for website, the key words of the website name setting, website logo,website introduction, contact us.');?></div></div>
                   	<div style="border-bottom:dotted 1px #CCC;"><div class="index_2" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_qq', 'admin_list'); ?>"><?php _e('Services');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('You can settle this function here, the normal online and immediate communication tool for helping.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_3" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_statistics', 'admin_list'); ?>"><?php _e('Statistics');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('If you want to know the volume of visiting, where these visiting come from..Etc, please add the calculation code.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_4" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_friendlink', 'admin_list'); ?>"><?php _e('Hot Links');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Please add the favorite links here.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_5" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_backup', 'admin_list'); ?>"><?php _e('Data Bakup/Recovery');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Backup data or import data.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_6" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_attachment', 'admin_list'); ?>"><?php _e('Image Watermark/Thumb');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Image watermark or thumb setting.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_7" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_advert', 'admin_list'); ?>"><?php _e('Advert Tool');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Advert setting.');?></div></div>
                    <div style="border-bottom:dotted 1px #CCC;"><div class="index_8" style="margin-left:30px;">&nbsp;</div><div style="float:left; width:125px; margin-left:30px;line-height:40px;color:#67B4E2;"><a href="<?php echo Html::uriquery('mod_sitestarmaker', 'admin_list'); ?>"><?php _e('Picture Tool');?></a></div><div style="overflow:hidden;line-height:40px;_width:400px; _overflow:hidden;"><?php _e('Logo and Banner setting.');?></div></div>
					<?php }?>
<br />
			
            </div>
        </div>